//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account info.
        /// </summary>
        internal static string accountinfo {
            get {
                return ResourceManager.GetString("accountinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin page.
        /// </summary>
        internal static string adminpage {
            get {
                return ResourceManager.GetString("adminpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amazon Germany.
        /// </summary>
        internal static string amzde {
            get {
                return ResourceManager.GetString("amzde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string certificate {
            get {
                return ResourceManager.GetString("certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string changepass {
            get {
                return ResourceManager.GetString("changepass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category.
        /// </summary>
        internal static string chondanhmuc {
            get {
                return ResourceManager.GetString("chondanhmuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da Nang.
        /// </summary>
        internal static string danang {
            get {
                return ResourceManager.GetString("danang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string dangky {
            get {
                return ResourceManager.GetString("dangky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seller Register .
        /// </summary>
        internal static string dangkybanhang {
            get {
                return ResourceManager.GetString("dangkybanhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string dangnhap {
            get {
                return ResourceManager.GetString("dangnhap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string dangxuat {
            get {
                return ResourceManager.GetString("dangxuat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOT DEAL.
        /// </summary>
        internal static string dealhot {
            get {
                return ResourceManager.GetString("dealhot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NEW SALES OFF.
        /// </summary>
        internal static string dealnew {
            get {
                return ResourceManager.GetString("dealnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order List.
        /// </summary>
        internal static string dsdonhang {
            get {
                return ResourceManager.GetString("dsdonhang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Diff List.
        /// </summary>
        internal static string dsdonhangmuaho {
            get {
                return ResourceManager.GetString("dsdonhangmuaho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string find {
            get {
                return ResourceManager.GetString("find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVINGS DELIVERY.
        /// </summary>
        internal static string giaohang {
            get {
                return ResourceManager.GetString("giaohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        internal static string giohang {
            get {
                return ResourceManager.GetString("giohang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SENDING GIFT.
        /// </summary>
        internal static string guiqua {
            get {
                return ResourceManager.GetString("guiqua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hà Nội.
        /// </summary>
        internal static string han {
            get {
                return ResourceManager.GetString("han", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha Noi.
        /// </summary>
        internal static string hanoi {
            get {
                return ResourceManager.GetString("hanoi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP.HCM.
        /// </summary>
        internal static string hcm {
            get {
                return ResourceManager.GetString("hcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Smua.
        /// </summary>
        internal static string introduce {
            get {
                return ResourceManager.GetString("introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khác.
        /// </summary>
        internal static string khac {
            get {
                return ResourceManager.GetString("khac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIP FROM JAPAN.
        /// </summary>
        internal static string muahangnhat {
            get {
                return ResourceManager.GetString("muahangnhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIP FROM AUSTRALIA.
        /// </summary>
        internal static string muahanguc {
            get {
                return ResourceManager.GetString("muahanguc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIP COD.
        /// </summary>
        internal static string muashipho {
            get {
                return ResourceManager.GetString("muashipho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCTS.
        /// </summary>
        internal static string productcat {
            get {
                return ResourceManager.GetString("productcat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put product name fo find.
        /// </summary>
        internal static string productnametofind {
            get {
                return ResourceManager.GetString("productnametofind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        internal static string quenmk {
            get {
                return ResourceManager.GetString("quenmk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string support {
            get {
                return ResourceManager.GetString("support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acount.
        /// </summary>
        internal static string taikhoan {
            get {
                return ResourceManager.GetString("taikhoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string thanhtoan {
            get {
                return ResourceManager.GetString("thanhtoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View all.
        /// </summary>
        internal static string viewall {
            get {
                return ResourceManager.GetString("viewall", resourceCulture);
            }
        }
    }
}
