//-- ------------------------------------------------------------
//-- Company name  :  DTGSOFT 
//-- Class name    :  clsOrderDiffsBase
//-- Creation date :  03/08/2018
//-- Created by    :  
//-- Description   :  
//-- Generated by  :  DTG Class Generator
//-- ------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Data; 

namespace OnChotto.Models.Dao
{
	public abstract class  OrderDiffsBase : OnChotto.Models.Dao.BaseObject
    {
		#region  Constants
		public override String EntityTableName { get { return "OrderDiffs"; } set { base.EntityTableName = value; } }
		public override String EntityProcedureName { get { return "sp_OrderDiffs"; } set { base.EntityProcedureName = value; } }
		public override String EntityProcedureNameUser { get { return "usp_OrderDiffs"; } set { base.EntityProcedureNameUser = value; } }

		#endregion  

		#region  Variables

		#endregion  

		#region  Constructors
		public OrderDiffsBase()
			: base(DataAccess.AppConnectionString)
		{
		}

		public OrderDiffsBase(string connectionString)
			: base(connectionString)
		{
		}

		public OrderDiffsBase(DataAccess dal)
			: base(dal)
		{
		}

		protected override void Initialize()
		{
			//Entity Object Name
			base.EntityTableName = EntityTableName;
			base.EntityProcedureName = EntityProcedureName;

			//Table Columns Name
			FieldNames.Add("Id");
			FieldNames.Add("UserId");
			FieldNames.Add("StatusId");
			FieldNames.Add("TotalWeight");
			FieldNames.Add("TotalAmount");
			FieldNames.Add("IsDeposit");
			FieldNames.Add("Ispayenough");
			FieldNames.Add("PaymentMethodId");
			FieldNames.Add("MAWB");
			FieldNames.Add("ReceiveName");
			FieldNames.Add("DistrictId");
			FieldNames.Add("ProvinceId");
			FieldNames.Add("ReceiveEmail");
			FieldNames.Add("ReceiveAddress");
			FieldNames.Add("ReceivePhone");
			FieldNames.Add("Note");
			FieldNames.Add("OrderDate");
			FieldNames.Add("RequireDate");

			//Primary Key Columns Name
			FieldKeys.Add("Id");
		}
		#endregion  

		#region  Properties
		public System.Int32 Id
		{
			get;
			set;
		}
		public System.String UserId
		{
			get;
			set;
		}
		public System.Int32 StatusId
		{
			get;
			set;
		}
		public System.Decimal TotalWeight
		{
			get;
			set;
		}
		public System.Decimal TotalAmount
		{
			get;
			set;
		}
		public System.Boolean IsDeposit
		{
			get;
			set;
		}
		public System.Boolean Ispayenough
		{
			get;
			set;
		}
		public System.Int32 PaymentMethodId
		{
			get;
			set;
		}
		public System.String MAWB
		{
			get;
			set;
		}
		public System.String ReceiveName
		{
			get;
			set;
		}
		public System.String DistrictId
		{
			get;
			set;
		}
		public System.String ProvinceId
		{
			get;
			set;
		}
		public System.String ReceiveEmail
		{
			get;
			set;
		}
		public System.String ReceiveAddress
		{
			get;
			set;
		}
		public System.String ReceivePhone
		{
			get;
			set;
		}
		public System.String Note
		{
			get;
			set;
		}
		public System.DateTime OrderDate
		{
			get;
			set;
		}
		public System.DateTime RequireDate
		{
			get;
			set;
		}

		#endregion  

		#region  Methods


		public override int Insert()
		{
			OutputObject = null;
			try
			{
				DataAccessObject.ClearParam();
				DataAccessObject.InputDefaultParams();
				DataAccessObject.InputParams("Action", "Insert");
				DataAccessObject.InputParams("Id", Id);
				DataAccessObject.InputParams("UserId", UserId);
				DataAccessObject.InputParams("StatusId", StatusId);
				DataAccessObject.InputParams("TotalWeight", TotalWeight);
				DataAccessObject.InputParams("TotalAmount", TotalAmount);
				DataAccessObject.InputParams("IsDeposit", IsDeposit);
				DataAccessObject.InputParams("Ispayenough", Ispayenough);
				DataAccessObject.InputParams("PaymentMethodId", PaymentMethodId);
				DataAccessObject.InputParams("MAWB", MAWB);
				DataAccessObject.InputParams("ReceiveName", ReceiveName);
				DataAccessObject.InputParams("DistrictId", DistrictId);
				DataAccessObject.InputParams("ProvinceId", ProvinceId);
				DataAccessObject.InputParams("ReceiveEmail", ReceiveEmail);
				DataAccessObject.InputParams("ReceiveAddress", ReceiveAddress);
				DataAccessObject.InputParams("ReceivePhone", ReceivePhone);
				DataAccessObject.InputParams("Note", Note);
				DataAccessObject.InputParams("OrderDate", OrderDate);
				DataAccessObject.InputParams("RequireDate", RequireDate);
				int intResult = DataAccessObject.ExecuteNonQuery(EntityProcedureName, DataAccessObject.ParamNames, DataAccessObject.ParamValues, ref OutputObject);

				if (OutputObject != null && OutputObject.Length > 0)
				{
					Id = DataAccess.CorrectValue(OutputObject.GetValue("Id").ToString(), System.Int32.MinValue);
				}

				return intResult;
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override int Update()
		{
			try
			{
				DataAccessObject.ClearParam();
				DataAccessObject.InputDefaultParams();
				DataAccessObject.InputParams("Action", "Update");
				DataAccessObject.InputParams("Id", Id);
				DataAccessObject.InputParams("UserId", UserId);
				DataAccessObject.InputParams("StatusId", StatusId);
				DataAccessObject.InputParams("TotalWeight", TotalWeight);
				DataAccessObject.InputParams("TotalAmount", TotalAmount);
				DataAccessObject.InputParams("IsDeposit", IsDeposit);
				DataAccessObject.InputParams("Ispayenough", Ispayenough);
				DataAccessObject.InputParams("PaymentMethodId", PaymentMethodId);
				DataAccessObject.InputParams("MAWB", MAWB);
				DataAccessObject.InputParams("ReceiveName", ReceiveName);
				DataAccessObject.InputParams("DistrictId", DistrictId);
				DataAccessObject.InputParams("ProvinceId", ProvinceId);
				DataAccessObject.InputParams("ReceiveEmail", ReceiveEmail);
				DataAccessObject.InputParams("ReceiveAddress", ReceiveAddress);
				DataAccessObject.InputParams("ReceivePhone", ReceivePhone);
				DataAccessObject.InputParams("Note", Note);
				DataAccessObject.InputParams("OrderDate", OrderDate);
				DataAccessObject.InputParams("RequireDate", RequireDate);
				return DataAccessObject.ExecuteNonQuery(EntityProcedureName, DataAccessObject.ParamNames, DataAccessObject.ParamValues);
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override int Delete()
		{
			OutputObject = null;
			try
			{
				DataAccessObject.ClearParam();
				DataAccessObject.InputDefaultParams();
				DataAccessObject.InputParams("Action", "Delete");
				DataAccessObject.InputParams("Id", Id);
				return DataAccessObject.ExecuteNonQuery(EntityProcedureName, DataAccessObject.ParamNames, DataAccessObject.ParamValues);
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override int Delete(System.Int32 id)
		{
			OutputObject = null;
			try
			{
				DataAccessObject.ClearParam();
				DataAccessObject.InputDefaultParams();
				DataAccessObject.InputParams("Action", "Delete");
				DataAccessObject.InputParams("Id", id);
				return DataAccessObject.ExecuteNonQuery(EntityProcedureName, DataAccessObject.ParamNames, DataAccessObject.ParamValues);
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override bool GetByKey(System.Int32 id)
		{
			OutputObject = null;
			DataTable dt = new DataTable(); 
			try
			{
				DataAccessObject.ClearParam();
				DataAccessObject.InputDefaultParams();
				DataAccessObject.InputParams("Action", "GetByKey");
				DataAccessObject.InputParams("Id", id);
				dt = DataAccessObject.ExecuteDataTable(EntityProcedureName, DataAccessObject.ParamNames, DataAccessObject.ParamValues);
				Reset();
				if(dt == null || dt.Rows.Count == 0) 
					return false;

				Fill(dt.Rows[0]);
				return true;
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override bool IsExists(System.Int32 id)
		{
			OutputObject = null;
			DataTable dt = new DataTable(); 
			try
			{
				DataAccessObject.ClearParam();
				DataAccessObject.InputDefaultParams();
				DataAccessObject.InputParams("Action", "IsExists");
				DataAccessObject.InputParams("Id", id);
				dt = DataAccessObject.ExecuteDataTable(EntityProcedureName, DataAccessObject.ParamNames, DataAccessObject.ParamValues);
				if(dt == null || dt.Rows.Count == 0) 
					return false;
				else
					return true;
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override DataTable GetAll()
		{
			return DataAccessObject.ExecuteDataTable(EntityProcedureName, "Action", new object[] {"GetAll"});
		}


		public override void Reset()
		{
			this.Id = Int32.MinValue;
			this.UserId = String.Empty;
			this.StatusId = Int32.MinValue;
			this.TotalWeight = Decimal.MinValue;
			this.TotalAmount = Decimal.MinValue;
			this.IsDeposit = false;
			this.Ispayenough = false;
			this.PaymentMethodId = Int32.MinValue;
			this.MAWB = String.Empty;
			this.ReceiveName = String.Empty;
			this.DistrictId = String.Empty;
			this.ProvinceId = String.Empty;
			this.ReceiveEmail = String.Empty;
			this.ReceiveAddress = String.Empty;
			this.ReceivePhone = String.Empty;
			this.Note = String.Empty;
			this.OrderDate = DateTime.MinValue;
			this.RequireDate = DateTime.MinValue;
		}


		public override void Fill(DataRow row)
		{
			Reset();
			if(row.Table.Columns.Contains("Id"))
				this.Id = DataAccess.CorrectValue(row["Id"], Id);
			if(row.Table.Columns.Contains("UserId"))
				this.UserId = DataAccess.CorrectValue(row["UserId"], UserId);
			if(row.Table.Columns.Contains("StatusId"))
				this.StatusId = DataAccess.CorrectValue(row["StatusId"], StatusId);
			if(row.Table.Columns.Contains("TotalWeight"))
				this.TotalWeight = DataAccess.CorrectValue(row["TotalWeight"], TotalWeight);
			if(row.Table.Columns.Contains("TotalAmount"))
				this.TotalAmount = DataAccess.CorrectValue(row["TotalAmount"], TotalAmount);
			if(row.Table.Columns.Contains("IsDeposit"))
				this.IsDeposit = DataAccess.CorrectValue(row["IsDeposit"], IsDeposit);
			if(row.Table.Columns.Contains("Ispayenough"))
				this.Ispayenough = DataAccess.CorrectValue(row["Ispayenough"], Ispayenough);
			if(row.Table.Columns.Contains("PaymentMethodId"))
				this.PaymentMethodId = DataAccess.CorrectValue(row["PaymentMethodId"], PaymentMethodId);
			if(row.Table.Columns.Contains("MAWB"))
				this.MAWB = DataAccess.CorrectValue(row["MAWB"], MAWB);
			if(row.Table.Columns.Contains("ReceiveName"))
				this.ReceiveName = DataAccess.CorrectValue(row["ReceiveName"], ReceiveName);
			if(row.Table.Columns.Contains("DistrictId"))
				this.DistrictId = DataAccess.CorrectValue(row["DistrictId"], DistrictId);
			if(row.Table.Columns.Contains("ProvinceId"))
				this.ProvinceId = DataAccess.CorrectValue(row["ProvinceId"], ProvinceId);
			if(row.Table.Columns.Contains("ReceiveEmail"))
				this.ReceiveEmail = DataAccess.CorrectValue(row["ReceiveEmail"], ReceiveEmail);
			if(row.Table.Columns.Contains("ReceiveAddress"))
				this.ReceiveAddress = DataAccess.CorrectValue(row["ReceiveAddress"], ReceiveAddress);
			if(row.Table.Columns.Contains("ReceivePhone"))
				this.ReceivePhone = DataAccess.CorrectValue(row["ReceivePhone"], ReceivePhone);
			if(row.Table.Columns.Contains("Note"))
				this.Note = DataAccess.CorrectValue(row["Note"], Note);
			if(row.Table.Columns.Contains("OrderDate"))
				this.OrderDate = DataAccess.CorrectValue(row["OrderDate"], OrderDate);
			if(row.Table.Columns.Contains("RequireDate"))
				this.RequireDate = DataAccess.CorrectValue(row["RequireDate"], RequireDate);
		}


		public override int UpdateTable(DataSet dataSource)
		{
			try
			{
				return DataAccessObject.UpdateTable(dataSource, EntityProcedureName, "Insert", "Update", "Delete");
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override int UpdateTable(DataTable dataSource)
		{
			try
			{
				return DataAccessObject.UpdateTable(dataSource, EntityProcedureName, "Insert", "Update", "Delete");
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override int UpdateTable(DataSet dataSource, string commandText, string[] paramNames)
		{
			try
			{
				return DataAccessObject.UpdateTable(dataSource, commandText, "Insert", "Update", "Delete", paramNames);
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}


		public override int UpdateTable(DataTable dataSource, string commandText, string[] paramNames)
		{
			try
			{
				return DataAccessObject.UpdateTable(dataSource, commandText, "Insert", "Update", "Delete", paramNames);
			}
			catch (Exception ex)
			{
				throw ex; 
			}
		}

		#endregion  

	}
}
