//-- ------------------------------------------------------------
//-- Company name  :  DTGSOFT 
//-- Class name    :  clsOrderDetailDiff
//-- Creation date :  03/08/2018
//-- Created by    :  
//-- Description   :  
//-- Generated by  :  DTG Class Generator
//-- ------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Data; 
namespace OnChotto.Models.Dao
{
	public class clsOrderDetailDiff : OnChotto.Models.Dao.clsOrderDetailDiffBase
	{
		#region  Constants

		#endregion  

		#region  Variables

		#endregion  

		#region  Constructors
		public clsOrderDetailDiff()
			: base(DataAccess.AppConnectionString)
		{
		}

		public clsOrderDetailDiff(string connectionString)
			: base(connectionString)
		{
		}

		public clsOrderDetailDiff(DataAccess dal)
			: base(dal)
		{
		}

		#endregion  

		#region  Developers

		#endregion  

	}
}
